In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
iris_dataset = load_iris()
X, y = load_iris(return_X_y=True)
print(X, y, sep='\n')

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
print(iris_dataset['data'])
print(f"shape of dta: {iris_dataset['data'].shape}")
print(iris_dataset['feature_names'])
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
train_input, test_input, train_label, test_label = train_test_split(X, y , test_size=0.5, random_state=3)

In [7]:
knn = KNeighborsClassifier(n_neighbors =1)

In [8]:
knn.fit(train_input, train_label)

KNeighborsClassifier(n_neighbors=1)

In [10]:
predict_label = knn.predict(test_input)
print(predict_label)

[0 0 0 0 0 2 1 0 2 1 1 0 1 1 2 0 2 2 2 0 2 2 2 1 0 2 2 1 1 1 0 0 2 1 0 0 1
 0 2 1 2 1 0 0 2 1 0 2 2 1 0 0 2 1 1 0 2 0 2 1 0 0 2 2 0 0 1 2 2 0 2 1 0 0
 2]


In [13]:
import numpy as np
print(f"test accuracy : {np.mean(predict_label == test_label)}")

test accuracy : 0.96


In [37]:
import pandas as pd
dataset=pd.read_csv('iris.csv')

train_input, test_input, train_label, test_label = train_test_split(X, y , test_size=0.5, random_state=3)
knn2=KNeighborsClassifier(n_neighbors=1)
print(knn2)
knn2.fit(train_input,train_label)

predict_label2=knn2.predict(test_input)
print(predict_label2)

KNeighborsClassifier(n_neighbors=1)
[0 0 0 0 0 2 1 0 2 1 1 0 1 1 2 0 2 2 2 0 2 2 2 1 0 2 2 1 1 1 0 0 2 1 0 0 1
 0 2 1 2 1 0 0 2 1 0 2 2 1 0 0 2 1 1 0 2 0 2 1 0 0 2 2 0 0 1 2 2 0 2 1 0 0
 2]


In [35]:
df_wine = pd.read_csv('./winequality-red.csv')
print(df_wine)
X_train,X_test,y_train,y_test=train_test_split(dataset,dataset.Species,test_size=0.5)
knn3=KNeighborsClassifier(n_neighbors=1)
print(knn3)
knn2.fit(train_input,train_label)

predict_label3=knn3.predict(test_input)
print(predict_label3)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [25]:
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.5, random_state=3)
gnb = GaussianNB()

In [29]:
y_pred = gnb.fit(X_train,y_train).predict(X_test)
print("number of misabeled points out of a total %d points:%d" %
      (X_test.shape[0], (y_test != y_pred).sum()))

number of misabeled points out of a total 75 points:3


In [38]:
print(y_pred)

[0 0 0 0 0 2 1 0 2 1 1 0 1 1 2 0 1 2 2 0 2 2 2 1 0 2 2 1 1 1 0 0 2 1 0 0 2
 0 2 1 2 1 0 0 2 1 0 2 2 1 0 0 2 1 1 0 2 0 2 1 0 0 2 2 0 0 1 2 2 0 2 1 0 0
 2]


In [49]:
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS

In [50]:
temp="Brave Girls you ready? 그 날을 잊지 못해 baby"

In [53]:
wordcloud = WordCloud(font_path='NanumGothic-Regular.ttf',
                     max_words=100,
                     width=800,
                     height=600,
                     max_font_size=150).generate(temp)
wordcloud.to_file('wordcloud.png')

In [78]:
from PIL import Image

icon=Image.open('masking_image.png').convert("RGBA")
mask=Image.new("RGB",icon.size,(255,255,255))
mask.paste(icon,icon)
mask=np.array(mask)

wordcloud=WordCloud(font_path='NanumGothic-Regular.ttf',background_color="black",max_words=1000,mask=mask,
                   max_font_size=100,random_state=42).generate(temp)
wordcloud.to_file("masking.png")

In [81]:
spwords=set(STOPWORDS)
spwords.add('hey')

In [83]:
temp='''지번주소
서울특별시 강남구 역삼동 813-4 지하 1층 코드케이
서울특별시 강남구 역삼동 815
서울특별시 강남구 역삼동 827-37 지하1층 키이스케이프 강남 더오름
서울특별시 강남구 역삼동 818-5
서울특별시 강남구 역삼동 817-21
서울특별시 강남구 역삼동 824-25
서울특별시 강남구 역삼동 619-28 메트로빌딩 B2층
서울특별시 강남구 논현동 201-6
서울특별시 강남구 역삼동 818-13 지하1층
서울특별시 강남구 역삼동 817-18
서울특별시 강남구 역삼동 811-6 지하1층
서울특별시 강남구 역삼동 826-29 우정에쉐르1 지하1층
서울특별시 강남구 역삼동 619-2
서울특별시 강남구 역삼동 813-13
서울특별시 강남구 역삼동 618-3
서울특별시 강남구 신사동 541-15
서울특별시 강남구 신사동 537 석천빌딩 4층
서울특별시 강남구 역삼동 814-1
서울특별시 강남구 역삼동 809-6 현도빌딩 지하1층
서울특별시 강남구 신사동 531
서울특별시 강남구 역삼동 817-36
서울특별시 강남구 역삼동 825-1
서울특별시 강남구 역삼동 827-14
서울특별시 강남구 대치동 897-28
서울특별시 강남구 신사동 663-7
서울특별시 강남구 역삼동 619-23
서울특별시 강남구 역삼동 637-20 도연빌딩 지하1층
서울특별시 강남구 역삼동 818-4
서울특별시 강남구 역삼동 815
서울특별시 강남구 역삼동 814-1
서울특별시 강동구 천호동 453-22
서울특별시 강북구 수유동 229-46
서울특별시 강북구 수유동 229-35
서울특별시 강북구 수유동 174-14
서울특별시 강서구 화곡동 861-8
서울특별시 관악구 신림동 75-41
서울특별시 관악구 신림동 1640-1 지하1층
서울특별시 관악구 신림동 1639-27
서울특별시 관악구 신림동 1639-23 4층 더코드
서울특별시 관악구 봉천동 1601-2
서울특별시 관악구 신림동 1638-23
서울특별시 관악구 신림동 1640-14 지하1층
서울특별시 관악구 신림동 1641-2
서울특별시 광진구 화양동 50-2
서울특별시 광진구 자양동 17-5
서울특별시 광진구 자양동 17-5 별관 2,3층
서울특별시 광진구 화양동 8-8
서울특별시 광진구 자양동 10-1
서울특별시 광진구 화양동 48-3 지하04,05,06호
서울특별시 광진구 군자동 361-27
서울특별시 광진구 화양동 7-12
서울특별시 광진구 자양동 24-2 지하1층
서울특별시 광진구 화양동 9-47
서울특별시 광진구 화양동 49-11 동성빌딩 지하1층
서울특별시 광진구 화양동 48-31 지하1층
서울특별시 광진구 군자동 503
서울특별시 광진구 자양동 5-70
서울특별시 광진구 화양동 48-4 지하 1층
서울특별시 광진구 화양동 21-23
서울특별시 광진구 자양동 9-31
서울특별시 광진구 군자동 361-32
서울특별시 광진구 화양동 3-22
서울특별시 광진구 화양동 9-66
서울특별시 광진구 화양동 15-54 2층 트루이스케이프룸 건대점
서울특별시 광진구 화양동 9-89
서울특별시 구로구 구로동 1124-54
서울특별시 노원구 상계동 349-51 경일빌딩 3층
서울특별시 노원구 상계동 357-8 신일빌딩 6층
서울특별시 노원구 상계동 331-8
서울특별시 동대문구 회기동 42-43 3층
서울특별시 동작구 사당동 139-88 3층
서울특별시 동작구 노량진동 118-8
서울특별시 동작구 사당동 1007-45
서울특별시 마포구 서교동 400-3
서울특별시 마포구 서교동 361-16
서울특별시 마포구 서교동 338-48
서울특별시 마포구 서교동 355-15
서울특별시 마포구 서교동 407-27
서울특별시 마포구 서교동 396-46
서울특별시 마포구 상수동 86-22
서울특별시 마포구 서교동 407-2 6층
서울특별시 마포구 서교동 339-5
서울특별시 마포구 서교동 358-123
서울특별시 마포구 서교동 408-27 보리수빌딩 지하1층
서울특별시 마포구 서교동 408-18
서울특별시 마포구 서교동 360-3
서울특별시 마포구 서교동 358-46
서울특별시 마포구 서교동 410-9
서울특별시 마포구 서교동 398-1
서울특별시 마포구 상수동 317-4
서울특별시 마포구 동교동 147-31
서울특별시 마포구 서교동 404-5
서울특별시 마포구 서교동 325-26
서울특별시 마포구 서교동 364-15
서울특별시 마포구 서교동 340-4 3층 마스터키 홍대점
서울특별시 마포구 서교동 405-13 3층
서울특별시 마포구 서교동 395-17 예랑빌딩 4층
서울특별시 마포구 서교동 364-4
서울특별시 마포구 서교동 366-25
서울특별시 마포구 서교동 331-18 3층
서울특별시 마포구 서교동 362-4
서울특별시 마포구 서교동 366-8
서울특별시 마포구 서교동 369-4 7F 엑스케이프 홍대점
서울특별시 마포구 서교동 340-5
서울특별시 마포구 서교동 405-11
서울특별시 마포구 서교동 396-36
서울특별시 마포구 합정동 393-18
서울특별시 마포구 서교동 358-91
서울특별시 마포구 동교동 162-3
서울특별시 마포구 서교동 409-1 3층
서울특별시 마포구 서교동 403-1 4층
서울특별시 마포구 서교동 358-125
서울특별시 마포구 서교동 364-3 예원빌딩 4층
서울특별시 마포구 서교동 358-44 1층, 2층
서울특별시 마포구 서교동 409-17
서울특별시 마포구 동교동 184-24
서울특별시 마포구 서교동 355-3
서울특별시 마포구 서교동 366-7 3F
서울특별시 서대문구 창천동 5-23
서울특별시 서대문구 창천동 2-7
서울특별시 서대문구 창천동 9-20
서울특별시 서대문구 창천동 18-11
서울특별시 서대문구 창천동 33-9 지하1층
서울특별시 서대문구 창천동 52-130
서울특별시 서대문구 창천동 5-21 2층
서울특별시 서대문구 창천동 13-2
서울특별시 서대문구 창천동 31-20
서울특별시 서대문구 창천동 52-46
서울특별시 서대문구 창천동 31-92
서울특별시 서대문구 창천동 49-5
서울특별시 서대문구 창천동 2-23
서울특별시 서대문구 창천동 57-22
서울특별시 서대문구 창천동 46-3
서울특별시 서초구 서초동 1308-25
서울특별시 서초구 서초동 1308-10 월드상가 5층
서울특별시 서초구 서초동 1317-9
서울특별시 서초구 서초동 1302-38 지하1층
서울특별시 서초구 서초동 1302-24
서울특별시 서초구 서초동 1307-18 피렌체타워 5층
서울특별시 서초구 반포동 746-8
서울특별시 서초구 반포동 746-3
서울특별시 서초구 서초동 1307 지하1층
서울특별시 서초구 서초동 1308-5
서울특별시 서초구 서초동 1308-14 4층
서울특별시 서초구 반포동 739-24 지하 1층
서울특별시 서초구 서초동 1337-6
서울특별시 서초구 양재동 4-15
서울특별시 성동구 행당동 19-7
서울특별시 성동구 성수동2가 314-7 지하1층 101호
서울특별시 성동구 성수동2가 321-74 지하 1층
서울특별시 성북구 동선동1가 87 4층
서울특별시 성북구 동선동1가 49 세학빌딩 6층
서울특별시 송파구 잠실동 184-3 지하1층
서울특별시 송파구 잠실동 182-5 4층
서울특별시 송파구 잠실동 180-9 5층
서울특별시 송파구 잠실동 177-5
서울특별시 송파구 잠실동 179-3 3층, 4층
서울특별시 양천구 신정동 902-5
서울특별시 영등포구 영등포동3가 8-1
서울특별시 영등포구 영등포동3가 23-8 4층 셜록홈즈
서울특별시 용산구 한강로3가 40-999
서울특별시 용산구 원효로2가 8-27
서울특별시 은평구 갈현동 400-7 3층
서울특별시 종로구 명륜2가 21-18
서울특별시 종로구 동숭동 1-113
서울특별시 종로구 동숭동 1-54
서울특별시 종로구 동숭동 1-34
서울특별시 종로구 동숭동 1-37
서울특별시 종로구 동숭동 1-60 4층
서울특별시 종로구 명륜4가 8-1 지하2층
서울특별시 종로구 동숭동 1-65
서울특별시 종로구 동숭동 1-150
서울특별시 종로구 관철동 12-23
서울특별시 종로구 안국동 17-14
서울특별시 중구 명동2가 3-2
서울특별시 중구 명동2가 50-5 삼문빌딩 8층 뉴발란스매장 내
'''
wordcloud = WordCloud(font_path='NanumGothic-Regular.ttf',
                     max_words=100,
                     width=800,
                     height=600,
                     max_font_size=150).generate(temp)
wordcloud.to_file('wordcloud.png')
from PIL import Image

icon=Image.open('masking_image.png').convert("RGBA")
mask=Image.new("RGB",icon.size,(255,255,255))
mask.paste(icon,icon)
mask=np.array(mask)

wordcloud=WordCloud(font_path='NanumGothic-Regular.ttf',background_color="black",max_words=1000,mask=mask,
                   max_font_size=100,random_state=42).generate(temp)
wordcloud.to_file("masking.png")