### numpy doc : https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=random%20rand#numpy.random.rand

In [1]:
import numpy as np

# 1. 정규분포를 따르는 임의의 값을 가지는 행렬 x1 = (100,10)을 만드세요.

In [2]:
x1 = np.random.rand(100,10)

print(x1.shape)
print(x1)

(100, 10)
[[0.96244888 0.26741386 0.42800283 0.98009526 0.38547991 0.46749851
  0.38171706 0.4909486  0.96666671 0.5108026 ]
 [0.02048739 0.02499218 0.39022086 0.65771138 0.45016461 0.47981987
  0.10928059 0.86176382 0.91224032 0.12087054]
 [0.95634475 0.81558637 0.49831615 0.84715944 0.43452581 0.66052955
  0.83626856 0.67568716 0.53483913 0.84082018]
 [0.34245209 0.06842289 0.3087929  0.40424532 0.66065733 0.762142
  0.938661   0.59729186 0.93263859 0.26094347]
 [0.91752185 0.94157644 0.11405091 0.77605818 0.40856243 0.81482258
  0.94987399 0.13950481 0.5370239  0.01609167]
 [0.99985687 0.27590334 0.20385494 0.25011469 0.90188061 0.47875078
  0.37647903 0.88835066 0.89054097 0.54861611]
 [0.91782624 0.69846308 0.26030146 0.92422333 0.297363   0.26726401
  0.48976285 0.09073745 0.37010234 0.28551341]
 [0.91800782 0.79148867 0.45088229 0.69172024 0.69282208 0.61428368
  0.64368137 0.72624479 0.27235124 0.83127483]
 [0.68549666 0.17801595 0.14899615 0.03204243 0.03596596 0.21331589
  0.

# 2. 행렬 x1에서 행(20-70번째), 열(1-6) 까지만 잘라내세요.

In [3]:
x1 = x1[20:70, 1:6]

print(x1.shape)
print(x1)

(50, 5)
[[0.55937692 0.09512295 0.72295907 0.35004103 0.02720786]
 [0.20102273 0.59585507 0.73851713 0.306269   0.81821595]
 [0.16759587 0.43552721 0.57802037 0.69638439 0.45545516]
 [0.34523547 0.15632329 0.45615251 0.69108984 0.57807423]
 [0.08438101 0.18899889 0.04446918 0.10107481 0.63178763]
 [0.61463743 0.76986178 0.46822861 0.30834773 0.34119054]
 [0.58291928 0.72399496 0.79089289 0.64223086 0.27460046]
 [0.79971235 0.11195463 0.25070041 0.92749278 0.55348988]
 [0.9733201  0.07471909 0.95039418 0.4043765  0.68680019]
 [0.61589647 0.60431957 0.61782991 0.70108163 0.04243069]
 [0.09552545 0.71210986 0.05834623 0.71188766 0.82175408]
 [0.70550946 0.71487769 0.37199476 0.64280892 0.90079641]
 [0.77036216 0.37818364 0.66120152 0.10517987 0.27922487]
 [0.12799686 0.9556036  0.91825886 0.74215335 0.27961107]
 [0.48699729 0.21764388 0.7920429  0.58402457 0.88327181]
 [0.03774471 0.13017244 0.6212975  0.75348576 0.82232962]
 [0.88559532 0.36704846 0.07249724 0.57204307 0.91353525]
 [0.35

# 3. 잘라낸 행렬과 내적곱을 계산할 행렬 x2 = (?, 5)를 만드세요.

### x2의 값은 내적곱을 계산할 수 있는 알맞은 값을 찾으세요

In [8]:
#(50, 5) * (?, 5)
#(50, 5) * (5, 5) = (50, 5)

x2 = np.random.randn(5,5)

x2

array([[-0.46825675, -1.81625588,  2.48376318, -0.6726499 ,  0.01147844],
       [ 0.93972075,  0.86328171,  0.41791044,  0.80786334,  0.98983716],
       [ 0.73125394, -0.49260612, -0.26432732, -0.36993143, -1.11483682],
       [-1.367132  ,  1.71680226,  0.03903453, -0.06646538, -1.57341247],
       [-1.44422701, -0.89395434,  0.0850921 , -0.9817744 ,  0.99484583]])

# 4. x1과 x2을 서로 내적곱 y를 구하세요. 

In [5]:
y = np.dot(x1, x2)

print(y.shape)
print(y)

(50, 5)
[[ 1.27437844e+00  1.65262947e+00 -2.89571401e-01  3.41900156e-01
   5.09169658e-01]
 [ 1.49192897e+00  6.16196789e-01 -3.27983230e-01 -1.08226173e-02
   2.78478158e+00]
 [ 1.78473358e+00  9.19283153e-01 -3.39758269e-01  8.50641380e-01
   2.47488191e+00]
 [ 2.20395023e+00  5.29565073e-01 -8.51024465e-01  5.21451657e-01
   1.67465270e+00]
 [ 7.65790554e-01 -6.58640011e-01 -4.79086326e-01 -4.07866949e-01
   1.07673734e+00]
 [ 4.54917274e-01  7.56755430e-01  2.03519513e-01 -1.93939879e-01
   1.87551283e+00]
 [ 1.32637221e+00  1.62790652e+00  5.90358016e-02  5.86832189e-01
   2.43881649e+00]
 [ 2.50248979e+00  3.17459803e-01 -1.15517573e+00  3.58322248e-01
   1.06088562e+00]
 [ 2.48199064e+00  1.34423005e+00 -1.13906069e+00 -3.84519262e-01
   8.35396097e-01]
 [ 1.13870912e+00  1.60502430e+00  1.06688820e-01  7.46824604e-01
   1.83843691e+00]
 [ 1.39641129e+00 -5.85249774e-01 -3.51642113e-01  3.76505825e-01
   3.09210150e+00]
 [ 1.73445248e+00  1.39749272e-03 -6.10059480e-01 -2.4148

# 5. y의 전치행렬을 구하세요

In [6]:
yT = (y.T)

print(yT.shape)
print(yT)

(5, 50)
[[ 1.27437844e+00  1.49192897e+00  1.78473358e+00  2.20395023e+00
   7.65790554e-01  4.54917274e-01  1.32637221e+00  2.50248979e+00
   2.48199064e+00  1.13870912e+00  1.39641129e+00  1.73445248e+00
   7.42916048e-01  1.27218808e+00  2.64973997e+00  2.77805403e+00
   1.82350526e+00  2.32563294e-01  2.31926145e+00  1.81480386e+00
   4.90677952e-01  6.49193412e-01  1.90391456e+00  1.95582086e-01
   1.37578836e+00  2.38031012e+00  4.40153932e-02  1.61721316e+00
   2.91126107e+00  1.66463103e+00  1.35879002e+00  1.37095942e+00
   1.45056674e+00  1.44278637e+00  1.64602492e+00  3.09664986e+00
   1.20300048e+00  1.86637204e+00  1.26291021e+00  3.00511091e+00
   1.70479390e+00  1.12369599e+00  2.62201188e+00 -1.37448258e-01
   1.86277491e+00  2.18999563e-01  1.18103999e+00  2.04908351e+00
   1.80933198e+00  1.58904026e+00]
 [ 1.65262947e+00  6.16196789e-01  9.19283153e-01  5.29565073e-01
  -6.58640011e-01  7.56755430e-01  1.62790652e+00  3.17459803e-01
   1.34423005e+00  1.60502430e+00